### ISSUE TITLE
都道府県のみを管理するテーブルを作成する???

### ISSUE THREAD

**Issue by shushikata** [o-clock-inc/o-clock-backend#82]
都道府県のみを管理するテーブルを作成する

**Comment by shushikata** [comment]
今のところ作成予定のカラムは下記に記載する

id
name

**Comment by white-chocolate-55** [comment]
個人的にはした方が良いと思います！
ソースコードにベタ書きやyml管理だと、色々実装しづらそうです。
関東とか関西にグルーピングしたいとか、一定の順番でソートしたいとかそういうことがしたくなった時にAR使った方が楽だと思います。あとは、市区町村まで追加したくなった時に拡張が楽かなと思いました
